logic added to create posts, error added to POST /posts endpoint in .yml
boolean-uk/team-dev-server-c13 pull request #10
Opened 2024-09-05 10:37 UTC by JDC-horizons

2024-09-05 11:38 UTC, ezeikel commented on src/controllers/post.js
> +// ignore
Do we need this comment?

2024-09-05 11:38 UTC, ezeikel approved these changes

2024-09-05 12:48 UTC, JDC-horizons commented on src/controllers/post.js
> +// ignore
No, will delete

2024-09-05 13:06 UTC, th0jensen approved these changes

2024-09-05 13:34 UTC, dogezen requested changes
1) change where we are loading the prisma client
2) remove the auth code from the controller

2024-09-05 13:34 UTC, dogezen commented on src/controllers/post.js
> +const prisma = new PrismaClient()
don't create a new prisma client, import the globally available prisma client in `/utils/dbClient.js`

2024-09-05 13:34 UTC, dogezen commented on src/controllers/post.js
> +  const auth = req.headers.authorization
don't repeat the token validation code here, there's a middleware function called `validateAuthentication` that should be called in the router, before this controller function. In fact, the validation is already being called in the post router:

```js
router.post('/', validateAuthentication, create)
```

2024-09-05 13:34 UTC, dogezen commented on src/controllers/post.js
> +    const userId = decodedToken.id
you can get the userId from `req.user.id`

2024-09-06 11:25 UTC, ezeikel approved these changes

2024-09-06 14:42 UTC, dogezen approved these changes

2024-09-06 15:02 UTC, th0jensen approved these changes

2024-09-09 11:16 UTC, ezeikel approved these changes

2024-09-09 15:21 UTC, merged